version: '3'

services:
  cassandra-1:
    image: 10.0.0.222:5000/cassandra_3.9
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
    ports:
      - 7000
    deploy:
      placement:
        constraints:
          - node.role == worker

  cassandra-2:
    image: 10.0.0.222:5000/cassandra_3.9
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-2"
      CASSANDRA_SEEDS: "cassandra-1"
    ports:
      - 7000
    depends_on:
      - "cassandra-1"
    deploy:
      placement:
        constraints:
          - node.role == worker

  cassandra-3:
    image: 10.0.0.222:5000/cassandra_3.9
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-3"
      CASSANDRA_SEEDS: "cassandra-1"
    ports:
      - 7000
    depends_on:
      - "cassandra-1"
      - "cassandra-2"
    deploy:
      placement:
        constraints:
          - node.role == worker
networks:
  default:
    external:
      name: cassandra-net-1
